// This file will be auto-generated by Supabase CLI after running:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
//
// For now, these are manual type definitions matching our schema.

export type UserRole = "super_admin" | "admin" | "collaborator";
export type UserType = "system_user" | "virtual_profile";
export type AdjustmentType = "deduction" | "bonus" | "correction";
export type AuditAction = "created" | "updated" | "deleted";
export type CsvImportStatus = "pending" | "processing" | "completed" | "failed";

export interface Database {
  public: {
    Tables: {
      partners: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          description?: string | null;
          is_active?: boolean;
        };
      };
      product_types: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
        };
        Update: {
          name?: string;
          description?: string | null;
        };
      };
      products: {
        Row: {
          id: string;
          partner_id: string;
          name: string;
          description: string | null;
          product_type_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          name: string;
          description?: string | null;
          product_type_id: string;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          description?: string | null;
          product_type_id?: string;
          is_active?: boolean;
        };
      };
      users: {
        Row: {
          id: string;
          auth_user_id: string | null;
          user_type: UserType;
          name: string;
          email: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id?: string | null;
          user_type: UserType;
          name: string;
          email?: string | null;
          is_active?: boolean;
        };
        Update: {
          user_type?: UserType;
          name?: string;
          email?: string | null;
          is_active?: boolean;
        };
      };
      user_partner_roles: {
        Row: {
          id: string;
          user_id: string;
          partner_id: string;
          role: UserRole;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          partner_id: string;
          role: UserRole;
        };
        Update: {
          role?: UserRole;
        };
      };
      product_distributions: {
        Row: {
          id: string;
          product_id: string;
          user_id: string;
          percentage_share: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          user_id: string;
          percentage_share: number;
        };
        Update: {
          percentage_share?: number;
        };
      };
      taxes: {
        Row: {
          id: string;
          partner_id: string;
          name: string;
          description: string | null;
          percentage_rate: number;
          priority_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          name: string;
          description?: string | null;
          percentage_rate: number;
          priority_order: number;
          is_active?: boolean;
        };
        Update: {
          name?: string;
          description?: string | null;
          percentage_rate?: number;
          priority_order?: number;
          is_active?: boolean;
        };
      };
      exchange_rates: {
        Row: {
          id: string;
          partner_id: string;
          month: string;
          usd_to_mxn: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          month: string;
          usd_to_mxn: number;
          notes?: string | null;
        };
        Update: {
          usd_to_mxn?: number;
          notes?: string | null;
        };
      };
      monthly_reports: {
        Row: {
          id: string;
          partner_id: string;
          report_month: string;
          exchange_rate_id: string;
          total_usd: number;
          total_mxn: number;
          is_locked: boolean;
          created_at: string;
          updated_at: string;
          locked_at: string | null;
          locked_by: string | null;
        };
        Insert: {
          id?: string;
          partner_id: string;
          report_month: string;
          exchange_rate_id: string;
          total_usd?: number;
          total_mxn?: number;
          is_locked?: boolean;
        };
        Update: {
          total_usd?: number;
          total_mxn?: number;
          is_locked?: boolean;
          locked_at?: string | null;
          locked_by?: string | null;
        };
      };
      report_line_items: {
        Row: {
          id: string;
          report_id: string;
          user_id: string;
          product_id: string | null;
          product_name: string | null;
          percentage_applied: number | null;
          gross_usd: number;
          after_taxes_usd: number;
          tax_breakdown: Record<string, unknown> | null;
          adjustments_usd: number;
          final_usd: number;
          final_mxn: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          user_id: string;
          product_id?: string | null;
          product_name?: string | null;
          percentage_applied?: number | null;
          gross_usd: number;
          after_taxes_usd: number;
          tax_breakdown?: Record<string, unknown> | null;
          adjustments_usd?: number;
          final_usd: number;
          final_mxn: number;
        };
        Update: {
          adjustments_usd?: number;
          final_usd?: number;
          final_mxn?: number;
        };
      };
      adjustments: {
        Row: {
          id: string;
          monthly_report_id: string;
          user_id: string;
          adjustment_type: AdjustmentType;
          amount_usd: number;
          description: string;
          created_at: string;
          created_by: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          monthly_report_id: string;
          user_id: string;
          adjustment_type: AdjustmentType;
          amount_usd: number;
          description: string;
          created_by: string;
        };
        Update: {
          adjustment_type?: AdjustmentType;
          amount_usd?: number;
          description?: string;
        };
      };
      csv_uploads: {
        Row: {
          id: string;
          partner_id: string;
          report_month: string;
          filename: string;
          file_path: string | null;
          file_size: number | null;
          status: CsvImportStatus;
          row_count: number | null;
          error_message: string | null;
          monthly_report_id: string | null;
          created_at: string;
          created_by: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          partner_id: string;
          report_month: string;
          filename: string;
          file_path?: string | null;
          file_size?: number | null;
          status?: CsvImportStatus;
          row_count?: number | null;
          created_by: string;
        };
        Update: {
          status?: CsvImportStatus;
          row_count?: number | null;
          error_message?: string | null;
          monthly_report_id?: string | null;
          processed_at?: string | null;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          table_name: string;
          record_id: string;
          action_type: AuditAction;
          old_values: Record<string, unknown> | null;
          new_values: Record<string, unknown> | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: never; // Audit logs are only created via triggers
        Update: never;
      };
    };
  };
}
